homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM0
devices:
  '0x00124b00226b11bc':
    friendly_name: dev_downstairs
  '0x00158d00068b39cb':
    friendly_name: dev_upstairs
  '0x00158d00066972f2':
    friendly_name: '0x00158d00066972f2'
